[workspace]

resolver = "2"
members = [
  "nfa",
  "redirect",
  "tool",
  "server",
]

[workspace.package]
edition = "2021"
version = "0.0.0"

[workspace.dependencies]
nfa = { path="nfa" }
redirect = { path = "redirect" }
tool = { path = "tool" }
server = { path = "server" }

anyhow = "1.0.86"
clap = { version = "4.5.8", features = ["derive"]}
futures-util = "0.3.30"
html-builder = "0.5.1"
hyper = { version = "0.14", features = ["full"]}
itertools = "0.13.0"
lazy_static = "1.4.0"
notify = { version = "6.1.1", default-features = false, features = ["macos_kqueue"] }
serde_json = "1.0.120"
serde = { version = "1.0.203" , features = ["derive"] }
serde_path_to_error = "0.1.11"
tokio = { version = "1.38.0", features = ["full"]}
url = "2.5.2"
