name:                platypuslol
version:             0.1.0.0
github:              "mic47/platypuslol"
license:             BSD3
author:              "Michal Nánási"
maintainer:          "michal.nanasi@gmail.com"
copyright:           "MIT License"

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- resources/index.html
- resources/opensearch.xml
- resources/favicon.ico
- resources/favicon-16x16.png
- resources/favicon-32x32.png
- resources/favicon-96x96.png
- resources/commands.conf

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/mic47/platypuslol#readme>

dependencies:
- base >= 4.7 && < 5

# Copied from 
# https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/
# I should customize this eventually

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

default-extensions: [
  ApplicativeDo,
  BangPatterns,
  ConstraintKinds,
  DataKinds,
  DefaultSignatures,
  DeriveFoldable,
  DeriveFunctor,
  DeriveGeneric,
  DeriveLift,
  DeriveTraversable,
  DerivingStrategies,
  EmptyCase,
  ExistentialQuantification,
  FlexibleContexts,
  FlexibleInstances,
  FunctionalDependencies,
  GADTs,
  GeneralizedNewtypeDeriving,
  InstanceSigs,
  KindSignatures,
  LambdaCase,
  MultiParamTypeClasses,
  MultiWayIf,
  NamedFieldPuns,
  OverloadedStrings,
  PatternSynonyms,
  RankNTypes,
  ScopedTypeVariables,
  StandaloneDeriving,
  TupleSections,
  TypeApplications,
  TypeFamilies,
  TypeFamilyDependencies,
  TypeOperators,
]

library:
  source-dirs: src
  dependencies:
  - blaze-builder
  - blaze-html
  - blaze-markup
  - http-types
  - parsec
  - text
  - unordered-containers
  - utf8-string
  - wai
  - wai-extra
  - warp


executables:
  platypuslol-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - platypuslol
    - warp
    - warp-tls
    - wai
    - text
    - http-types
    - blaze-builder
    - optparse-applicative
    - utf8-string
    - unordered-containers

tests:
  platypuslol-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - platypuslol
